version: "3.8"

services:
  backend:
    build: ./backend
    container_name: enterness-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: enterness-frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always
